### PR TITLE
Add tests for renew commands

### PR DESCRIPTION
**Pull request by kaykurokawa**
Renew command tests.
Goes with https://github.com/lbryio/lbry/pull/1009

### CODE REVIEW

**Comment by lyoshenka** [comment]
@eukreign this may be useful for you for orchestr8 as well

**Comment by eukreign** [comment]
Would like to merge this but travis-ci has failed this build.

**Comment by tzarebczan** [comment]
@IGassmann / @lyoshenka can you look into why travis is failing?

**Comment by lyoshenka** [comment]
I'll let kay or lex look at this. It's not gonna be something Igor or I can fix without a lot of digging.

**Comment by eukreign** [comment]
I can tackle this head on along with incorporating orchstr8 and getting it deployed to docker hub... but only after I'm done with the wallet. Someone else is welcome to beat me to it :-D

**Comment by alyssaoc** [comment]
closing, no longer needed

**Pull request closed without merging**
